@base_url = http://localhost:3001/api/

###Get Assets
GET {{base_url}}nodes/assets


### Get market data for a ticker
POST {{base_url}}langgraph/query-marketgraph
Content-Type: application/json

{
    "ticker": "aapl",
    "type": "crypto"
}



# {
#     "ticker": "AAPL",
#     "type": "stock"
# }